// Generates the CommonJS/ESM wrappers around oavg.js (the single source of the maths).
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync(new URL("./oavg.js", import.meta.url), "utf8");
const tail = "})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this));";
if (!src.trimEnd().endsWith(tail)) throw new Error("oavg.js footer changed; update build.mjs");
const body = src.trimEnd().slice(0, -tail.length) + "})(__root);\n";
const header = "// GENERATED by build.mjs from oavg.js - do not edit.\n";
const NAMES = ["version", "SPEC_VERSION", "PRECISIONS", "DEFAULT_PRECISION", "OAVGError", "loadRegistry", "getAnchor",
  "encode", "encodeGrid", "decode", "decodeGrid", "parse", "describe", "distance", "distanceM", "distanceFromAnchorM",
  "move", "shorten", "normalize", "cellPolygon", "nearestAnchor", "toGrid", "fromGrid"];

writeFileSync(new URL("./core.cjs", import.meta.url),
  header + "var __root = {};\n" + body + "module.exports = __root.OAVG;\n");
writeFileSync(new URL("./core.mjs", import.meta.url),
  header + "const __root = {};\n" + body + "const OAVG = __root.OAVG;\nexport default OAVG;\n" +
  "export const { " + NAMES.join(", ") + " } = OAVG;\n");

// The airport list comes from the Python package's CSV: one source of truth for both packages.
function parseCsv(text) {
  const rows = []; let row = [], field = "", q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) { if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; } else field += c; }
    else if (c === '"') q = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") { if (c === "\r" && text[i + 1] === "\n") i++; row.push(field); rows.push(row); row = []; field = ""; }
    else field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1);
}
const csv = parseCsv(readFileSync(new URL("../python/src/airportvector/anchors.csv", import.meta.url), "utf8"));
const head = csv.shift();
const col = n => { const i = head.indexOf(n); if (i < 0) throw new Error("anchors.csv missing column " + n); return i; };
const [iC, iLat, iLon, iN, iS] = [col("code"), col("lat"), col("lon"), col("name"), col("status")];
const anchors = csv.map(r => r[iS] && r[iS].trim() !== "active"
  ? { code: r[iC], lat: +r[iLat], lon: +r[iLon], name: r[iN], status: r[iS].trim() }
  : [r[iC], +r[iLat], +r[iLon], r[iN]]);
writeFileSync(new URL("./anchors.json", import.meta.url), JSON.stringify(anchors));
writeFileSync(new URL("./anchors.cjs", import.meta.url), header + "module.exports = " + JSON.stringify(anchors) + ";\n");
writeFileSync(new URL("./anchors.mjs", import.meta.url), header + "export default " + JSON.stringify(anchors) + ";\n");

writeFileSync(new URL("./index.cjs", import.meta.url), header +
  "const OAVG = require(\"./core.cjs\");\nOAVG.loadRegistry(require(\"./anchors.cjs\"));\nmodule.exports = OAVG;\n");
writeFileSync(new URL("./index.mjs", import.meta.url), header +
  "import OAVG from \"./core.mjs\";\nimport anchors from \"./anchors.mjs\";\nOAVG.loadRegistry(anchors);\nexport default OAVG;\n" +
  "export const { " + NAMES.join(", ") + " } = OAVG;\n");
console.log("built core.cjs core.mjs index.cjs index.mjs anchors.cjs anchors.mjs (" + anchors.length + " anchors)");
