// Parity with the Python reference implementation (vectors generated by airportvector 2.1.1 on PyPI).
const test = require("node:test");
const assert = require("node:assert/strict");
const av = require("..");
const V = require("./vectors.json");

test("encode matches Python at every precision", () => {
  for (const r of V.encode) for (const p of ["1km", "100m", "10m", "1m"])
    assert.equal(av.encode(r.lat, r.lon, p), r[p], `${r.lat},${r.lon} @${p}`);
});
test("decode matches Python to 1e-8 degrees", () => {
  for (const r of V.encode) {
    const d = av.decode(r["10m"]);
    assert.ok(Math.abs(d.lat - r.dlat) < 1e-8 && Math.abs(((d.lon - r.dlon + 540) % 360) - 180) < 1e-8, r["10m"]);
  }
});
test("describe matches Python exactly", () => {
  for (const r of V.encode) assert.equal(av.describe(r["10m"]), r.describe);
});
test("invalid codes throw OAVGError", () => {
  for (const c of V.invalid) assert.throws(() => av.parse(c), av.OAVGError, JSON.stringify(c));
});
